# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDvrtest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_dVR(self):
    self.driver.get("http://10.109.66.246:81/")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.ID, "loginUsername-inputEl").click()
    self.driver.find_element(By.ID, "loginUsername-inputEl").click()
    element = self.driver.find_element(By.ID, "loginUsername-inputEl")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "loginPassword-inputEl").click()
    self.driver.find_element(By.ID, "loginPassword-inputEl").send_keys("css@12345")
    self.driver.find_element(By.ID, "loginButton-btnIconEl").click()
    self.driver.find_element(By.ID, "button-1039-btnIconEl").click()
    self.driver.find_element(By.CSS_SELECTOR, "#menuitem-1027-textEl > span").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.ID, "ext-gen1151").click()
    self.driver.find_element(By.ID, "combobox-1061-inputEl").click()
    self.driver.find_element(By.ID, "ext-gen1232").click()
    self.driver.find_element(By.ID, "ext-comp-1062-inputEl").click()
    self.driver.find_element(By.ID, "ext-comp-1062-inputEl").click()
    element = self.driver.find_element(By.ID, "ext-comp-1062-inputEl")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "ext-comp-1059-innerCt").click()
    self.driver.find_element(By.ID, "ext-comp-1076-btnIconEl").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.ID, "ext-gen1159").click()
    self.driver.find_element(By.ID, "textfield-1090-inputEl").click()
    self.driver.find_element(By.ID, "textfield-1090-inputEl").click()
    element = self.driver.find_element(By.ID, "textfield-1090-inputEl")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "ext-comp-1091-inputEl").click()
    self.driver.find_element(By.ID, "ext-comp-1091-inputEl").click()
    element = self.driver.find_element(By.ID, "ext-comp-1091-inputEl")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "textfield-1094-inputEl").click()
    self.driver.find_element(By.ID, "textfield-1094-inputEl").click()
    element = self.driver.find_element(By.ID, "textfield-1094-inputEl")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "ext-comp-1084-innerCt").click()
    self.driver.find_element(By.ID, "ext-comp-1084-innerCt").click()
    element = self.driver.find_element(By.ID, "ext-comp-1084-innerCt")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "textfield-1095-inputEl").click()
    self.driver.find_element(By.ID, "textfield-1095-inputEl").click()
    element = self.driver.find_element(By.ID, "textfield-1095-inputEl")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "textfield-1095-inputEl").send_keys("cam@12345")
    self.driver.find_element(By.ID, "textfield-1097-inputEl").click()
    self.driver.find_element(By.ID, "textfield-1097-inputEl").click()
    element = self.driver.find_element(By.ID, "textfield-1097-inputEl")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "textfield-1097-inputEl").click()
    self.driver.find_element(By.ID, "textfield-1097-inputEl").click()
    element = self.driver.find_element(By.ID, "textfield-1097-inputEl")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "combobox-1110-inputEl").click()
    self.driver.find_element(By.ID, "ext-gen1459").click()
    self.driver.find_element(By.ID, "checkbox-1131-inputEl").click()
    self.driver.find_element(By.ID, "checkbox-1131-inputEl").click()
    element = self.driver.find_element(By.ID, "checkbox-1131-inputEl")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "ext-comp-1157-btnIconEl").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.ID, "ext-comp-1154-btnIconEl").click()
  
