# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    # Test name: Untitled
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://10.109.66.246:81/")
    # 2 | setWindowSize | 1552x840 | 
    self.driver.set_window_size(1552, 840)
    # 3 | click | id=loginUsername-inputEl | 
    self.driver.find_element(By.ID, "loginUsername-inputEl").click()
    # 4 | click | id=loginUsername-inputEl | 
    self.driver.find_element(By.ID, "loginUsername-inputEl").click()
    # 5 | doubleClick | id=loginUsername-inputEl | 
    element = self.driver.find_element(By.ID, "loginUsername-inputEl")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 6 | click | id=loginPassword-inputEl | 
    self.driver.find_element(By.ID, "loginPassword-inputEl").click()
    # 7 | type | id=loginPassword-inputEl | css@12345
    self.driver.find_element(By.ID, "loginPassword-inputEl").send_keys("css@12345")
    # 8 | click | id=loginButton-btnIconEl | 
    self.driver.find_element(By.ID, "loginButton-btnIconEl").click()
    # 9 | click | id=button-1039-btnIconEl | 
    self.driver.find_element(By.ID, "button-1039-btnIconEl").click()
    # 10 | click | css=#menuitem-1027-textEl > span | 
    self.driver.find_element(By.CSS_SELECTOR, "#menuitem-1027-textEl > span").click()
    # 11 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 12 | click | id=combobox-1061-inputEl | 
    self.driver.find_element(By.ID, "combobox-1061-inputEl").click()
    # 13 | click | id=combobox-1061-inputEl | 
    self.driver.find_element(By.ID, "combobox-1061-inputEl").click()
    # 14 | doubleClick | id=combobox-1061-inputEl | 
    element = self.driver.find_element(By.ID, "combobox-1061-inputEl")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 15 | click | id=ext-comp-1062-inputEl | 
    self.driver.find_element(By.ID, "ext-comp-1062-inputEl").click()
    # 16 | click | id=ext-comp-1062-inputEl | 
    self.driver.find_element(By.ID, "ext-comp-1062-inputEl").click()
    # 17 | doubleClick | id=ext-comp-1062-inputEl | 
    element = self.driver.find_element(By.ID, "ext-comp-1062-inputEl")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 18 | click | id=panel-1074-innerCt | 
    self.driver.find_element(By.ID, "panel-1074-innerCt").click()
    # 19 | click | id=ext-comp-1076-btnIconEl | 
    self.driver.find_element(By.ID, "ext-comp-1076-btnIconEl").click()
    # 20 | click | id=ext-gen1160 | 
    self.driver.find_element(By.ID, "ext-gen1160").click()
    # 21 | click | id=textfield-1090-inputEl | 
    self.driver.find_element(By.ID, "textfield-1090-inputEl").click()
    # 22 | click | id=textfield-1090-inputEl | 
    self.driver.find_element(By.ID, "textfield-1090-inputEl").click()
    # 23 | doubleClick | id=textfield-1090-inputEl | 
    element = self.driver.find_element(By.ID, "textfield-1090-inputEl")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 24 | click | id=ext-comp-1091-inputEl | 
    self.driver.find_element(By.ID, "ext-comp-1091-inputEl").click()
    # 25 | click | id=ext-comp-1091-inputEl | 
    self.driver.find_element(By.ID, "ext-comp-1091-inputEl").click()
    # 26 | doubleClick | id=ext-comp-1091-inputEl | 
    element = self.driver.find_element(By.ID, "ext-comp-1091-inputEl")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 27 | click | id=textfield-1094-inputEl | 
    self.driver.find_element(By.ID, "textfield-1094-inputEl").click()
    # 28 | click | id=textfield-1094-inputEl | 
    self.driver.find_element(By.ID, "textfield-1094-inputEl").click()
    # 29 | doubleClick | id=textfield-1094-inputEl | 
    element = self.driver.find_element(By.ID, "textfield-1094-inputEl")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 30 | click | id=textfield-1095-inputEl | 
    self.driver.find_element(By.ID, "textfield-1095-inputEl").click()
    # 31 | click | id=textfield-1095-inputEl | 
    self.driver.find_element(By.ID, "textfield-1095-inputEl").click()
    # 32 | doubleClick | id=textfield-1095-inputEl | 
    element = self.driver.find_element(By.ID, "textfield-1095-inputEl")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 33 | type | id=textfield-1095-inputEl | cam@12345
    self.driver.find_element(By.ID, "textfield-1095-inputEl").send_keys("cam@12345")
    # 34 | click | id=textfield-1097-inputEl | 
    self.driver.find_element(By.ID, "textfield-1097-inputEl").click()
    # 35 | click | id=textfield-1097-inputEl | 
    self.driver.find_element(By.ID, "textfield-1097-inputEl").click()
    # 36 | doubleClick | id=textfield-1097-inputEl | 
    element = self.driver.find_element(By.ID, "textfield-1097-inputEl")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 37 | click | id=ext-gen1365 | 
    self.driver.find_element(By.ID, "ext-gen1365").click()
    # 38 | click | id=ext-gen1459 | 
    self.driver.find_element(By.ID, "ext-gen1459").click()
    # 39 | click | id=ext-comp-1084-innerCt | 
    self.driver.find_element(By.ID, "ext-comp-1084-innerCt").click()
    # 40 | click | id=checkbox-1131-inputEl | 
    self.driver.find_element(By.ID, "checkbox-1131-inputEl").click()
    # 41 | click | id=checkbox-1131-inputEl | 
    self.driver.find_element(By.ID, "checkbox-1131-inputEl").click()
    # 42 | click | id=ext-gen1369 | 
    self.driver.find_element(By.ID, "ext-gen1369").click()
    # 43 | click | id=ext-gen1484 | 
    self.driver.find_element(By.ID, "ext-gen1484").click()
    # 44 | click | id=ext-comp-1113-inputEl | 
    self.driver.find_element(By.ID, "ext-comp-1113-inputEl").click()
    # 45 | click | id=ext-comp-1113-inputEl | 
    self.driver.find_element(By.ID, "ext-comp-1113-inputEl").click()
    # 46 | doubleClick | id=ext-comp-1113-inputEl | 
    element = self.driver.find_element(By.ID, "ext-comp-1113-inputEl")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 47 | click | id=ext-comp-1114-inputEl | 
    self.driver.find_element(By.ID, "ext-comp-1114-inputEl").click()
    # 48 | click | id=ext-comp-1114-inputEl | 
    self.driver.find_element(By.ID, "ext-comp-1114-inputEl").click()
    # 49 | doubleClick | id=ext-comp-1114-inputEl | 
    element = self.driver.find_element(By.ID, "ext-comp-1114-inputEl")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 50 | click | id=ext-comp-1121-inputEl | 
    self.driver.find_element(By.ID, "ext-comp-1121-inputEl").click()
    # 51 | click | id=ext-comp-1121-inputEl | 
    self.driver.find_element(By.ID, "ext-comp-1121-inputEl").click()
    # 52 | doubleClick | id=ext-comp-1121-inputEl | 
    element = self.driver.find_element(By.ID, "ext-comp-1121-inputEl")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 53 | click | id=ext-comp-1122-inputEl | 
    self.driver.find_element(By.ID, "ext-comp-1122-inputEl").click()
    # 54 | click | id=ext-comp-1122-inputEl | 
    self.driver.find_element(By.ID, "ext-comp-1122-inputEl").click()
    # 55 | doubleClick | id=ext-comp-1122-inputEl | 
    element = self.driver.find_element(By.ID, "ext-comp-1122-inputEl")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 56 | click | id=ext-comp-1157-btnIconEl | 
    self.driver.find_element(By.ID, "ext-comp-1157-btnIconEl").click()
  
